### ISSUE TITLE
Cannot enter more than 1 digit when using precision range

### ISSUE THREAD

**Issue by ragulka** [dm4t2/intl-number-input#12]
Using the lates version, `1.2.1`, it seems there's a bug, which can be [replicated in the playground](https://dm4t2.github.io/intl-number-input/playground.html).

1. Enable precision
2. Check "Use range"
3. Type `123` into the number field
4. **Only number 1 can be entered, the following keystrokes are ignored/discarded**
5. Uncheck "Use range"
6. Try typing `123` again
7. The input now correctly accepts all numbers

**Comment by dm4t2** [comment]
I followed your instructions and tried to reproduce this, but I can input any number with precision range enabled. What is your browser locale?

My exported options are:
```
{
  formatStyle: 'decimal',
  locale: undefined,
  currency: undefined,
  currencyDisplay: undefined,
  unit: undefined,
  unitDisplay: undefined,
  valueRange: undefined,
  precision: {
    min: 2,
    max: 5
  },
  hidePrefixOrSuffixOnFocus: true,
  hideGroupingSeparatorOnFocus: true,
  hideNegligibleDecimalDigitsOnFocus: true,
  autoDecimalDigits: false,
  exportValueAsInteger: false,
  autoSign: true,
  useGrouping: true
}
```

**Comment by ragulka** [comment]
@dm4t2 sorry for the delay! Oddly enough, I cannot reproduce this myself, either. I'm not sure what happened in-between, but I was definitely able to reproduce it both locally and on the playground. I'll let you know should I run into this again.
