### ISSUE TITLE
Why does component rerender break this?

### ISSUE THREAD

**Issue by 9mm** [dm4t2/intl-number-input#17]
I have no idea what could be causing this, I have fought with this for hours and I'm losing my mind.

At the top of my component you will notice:

```
@blur="onBlur"
:valid="meta.valid"
:touched="meta.touched"
:error="errorMessage"
```

The 3 props come from veeValidate, and the onBlur calls a vee method which updates those props (the meta object)

Whenever this gets updated, the entire component breaks and resets the input, presumably because the component is rerendering.

I made a sandbox. you will notice it adds $5000 automatically after 1 second. once that occurs, click in the box and immediately click out of it without typing and you will see the entire input clear.

https://codesandbox.io/s/jolly-cloud-4yysns?file=/src/components/AppInput.vue

**Comment by 9mm** [comment]
It looks like maybe its breaking because the component re-renders...  specifically this div wrapping the input:

```
  <div class="input-control" :class="{ 'input-error': showError }">
```

Is it that somehow the ref is getting lost or something when the component updates? How else can I preserve the ref?

**Comment by dm4t2** [comment]
Hi, the problem is not caused by the template ref. It's because the value of your `FormInput` component is not bound to the masked value via `v-model`.

I updated your CodeSandbox and now it works:
https://codesandbox.io/s/xenodochial-leftpad-fuc8lw?file=/src/components/FormInput.vue

Hope this helps 😉

**Comment by 9mm** [comment]
Hmm interesting, I was going to do that but I noticed if `modelValue` was set as a prop, but was NOT bound using `v-bind` it would still somehow change the value, as if it were doing it implicitly or something.

Thanks!

**Comment by 9mm** [comment]
@dm4t2 so this is just a side question... can you explain how it works fine without those extra attributes? That was ultimately what was confusing, and caused me to not add v-model.

1) adding a `props` key to the script with `modelValue`, but NOT adding any bindings in the actual template... it actually was affecting the value of the input. This lead me to believe there was some magic going on where it was automatically binding with modelValue or something, or vue was implicitly putting it on the input even though I never said `:model-value` or `v-model`

2) if you remove the `:error, :valid, :touched` keys (and leave v-model off) it works fine. https://codesandbox.io/s/jolly-cloud-4yysns?file=/src/components/FormInput.vue:57-69

It works well, I was just curious what is vue/this library doing to cause this behavior.

**Comment by dm4t2** [comment]
This is not caused by my library, it only writes the formatted input value. When used on a custom Vue input component that manages the value state on its own (`v-model`), then the state must be synced. Otherwise, it gets overridden or cleared on external changes.
