### ISSUE TITLE
Allow providing min & max precision

### ISSUE THREAD

**Issue by ragulka** [dm4t2/intl-number-input#3]
Thanks for fixing decimal format issues (#1)! I wanted to use this for a price input that allows a flexible number of decimals between a defined min and max precision. The idea is the same as the `minimumFractionDigits` and `maximumFractionDigits` options of the Intl API. I realize the same issue has been raised before in https://github.com/dm4t2/vue-currency-input/pull/261 - but I hope there's a way to add support to it in this package.

As mentioned in the above issue, it's extremely helpful in cases where a price or number input needs to have at least 2 decimal places, but may support more for higher precision (say 5), if necessary.

By looking at the [relevant source code](https://github.com/dm4t2/intl-number-input/blob/ee62d008791f93e57710fd794aa0272a58f82907/src/numberInput.ts#L144-L146) it doesn't look like the `hideNegligibleDecimalDigitsOnFocus` option would conflict with a precision range, as it only uses the `maximumFractionDigits` of the number format.

Could this be implemented or am I missing something? I'm happy to try and send a PR - I'm just not too confident with my TypeScript foo 😅

**Comment by dm4t2** [comment]
Now available in [v1.2.0](https://github.com/dm4t2/intl-number-input/releases/tag/v1.2.0) 🎉
