### ISSUE TITLE
hidePrefixOrSuffixOnFocus does not work as expected

### ISSUE THREAD

**Issue by ragulka** [dm4t2/intl-number-input#6]
Given the currency, unit or percent style, I would expect `hidePrefixOrSuffixOnFocus: true` to hide the prefix or suffix, well.. when the input is focused :smile:. However, in my testing, the behavior is different:

* Using `currency` or `unit`, the prefix/suffix is hidden only once I start typing. I would expect it to be hidden as soon as the input gains focus.
* Using `percent`, the prefix/suffix is _always_ hidden, whether the input is focused or not. I would expect it to be visible when not focused and only disappear when focused.

Note that `hidePrefixOrSuffixOnFocus: false` seems to work as expected.

**Comment by dm4t2** [comment]
I actually can not reproduce your `hidePrefixOrSuffixOnFocus` issues. 
The percent format issues should be fixed in v1.1.0 (see [bb81ba0](https://www.github.com/dm4t2/intl-number-input/commit/bb81ba03130a1ed4fee733cd181483ac110bdf7e))

https://stackblitz.com/edit/typescript-tbv3f1?file=index.ts

**Comment by ragulka** [comment]
> I actually can not reproduce your `hidePrefixOrSuffixOnFocus` issues.

Looks like the issue has indeed been fixed in 1.1.0 🎉  Thanks!
